/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import { useGLTF } from "@react-three/drei";
import { useRef } from "react";

export function GltfModel(props) {
    const { nodes, materials } = useGLTF("/astro.glb");
    const ref = useRef()
    
    return (
        <group ref={ref}{...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002.geometry}
                material={materials.body}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002_1.geometry}
                material={materials.tech}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002_2.geometry}
                material={materials.metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002_3.geometry}
                material={materials.body}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002_4.geometry}
                material={materials.metal}
            />
            </group>
    );
}

useGLTF.preload("/astro.glb");